[package]
name = "east_forest"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.4"
dotenv = "0.15.0"
serde = "1.0.219"
tokio = { version = "1.28.0", features = ["full"] }
tower-http = "0.6.6"
